### ISSUE TITLE
Adequação de campo de telefone

### ISSUE THREAD

**Issue by filiperochalopes** [willsf2021/login-register-bible-s-game#6]
Conforme já descrito em https://github.com/willsf2021/login-register-bible-s-game/pull/2#issuecomment-2493288564 referente a https://github.com/willsf2021/login-register-bible-s-game/pull/2 ;

![image](https://github.com/user-attachments/assets/7f348199-9b55-4c6d-8d57-20739a09120f)

O exemplo mostrado no placeholder está errado, só precisa de DDD e Número

**Comment by willsf2021** [comment]
Fixed
