### ISSUE TITLE
Redirecionamento de cadastro

### ISSUE THREAD

**Issue by filiperochalopes** [willsf2021/login-register-bible-s-game#7]
![image](https://github.com/user-attachments/assets/8f142547-992f-4037-a5d1-8ba01efbad6f)

Após realizar o cadastro, não somos redirecionados para página segura com o login realizado, [nem o formulário é limpo](https://formik.org/docs/migrating-v2#resetform) pelo contrário, ficamos na página.

Isso já tinha sido descrito em: https://github.com/willsf2021/login-register-bible-s-game/pull/2#issuecomment-2493288564 referente a #2 

> Ao cadastrar um novo usuário não temos nenhuma mensagem que foi cadastrado com sucesso. O usuário deve saber que foi cadastrado, o formulário limpo e ser direcionado para tela de login. Sem esses feedbacks acaba que o cliente cadastra vários usuários sem saber o que está fazendo, pois a impressão que temos é que não funcionou o fomulário. Aí quando cadastra novamente ele diz o erro que já existe um usuário como aquele e aquele  email.

> Para notificações tem um recurso simples que gosto de usar em protótipos assim que é o https://evandromacedo.github.io/react-simple-snackbar/

**Comment by filiperochalopes** [comment]
Acabei de notar que algumas alterações foram realizadas sim, eu não tinha atualizado o código aqui. Mas ao cadastrar com sucesso deve fazer login e ir para página segura, que no caso será um página de exemplo nesse momento. 

Você pode pegar como exemplo estudando a estrutura de:

https://github.com/filiperochalopes/sistema-evolucao-medica/blob/feature/first-week-features/reactapp/src/services/Context.jsx

https://github.com/filiperochalopes/sistema-evolucao-medica/blob/feature/first-week-features/reactapp/src/routes/PrivateRouter.jsx

https://github.com/filiperochalopes/sistema-evolucao-medica/blob/9f742afcbb3e4532850fcfd1b4b26a11c80fd7af/reactapp/src/routes/index.jsx#L13

Pode ser simplificado! Happy coding! 🚀

**Comment by willsf2021** [comment]
It has already been developed
